### ISSUE TITLE
New version of host.zip cannot open local link with space in it.

### ISSUE THREAD

**Issue by cooliooau** [hashedtomato3/open-local-link#1]
Hi there,

We noticed a bug in the new host.zip file. Once installed the new host.zip, it does not support local links with a space in it. For example: **C:\temp\Section 80.pdf**. Click the local link with space will show a CMD window.

The old version host.zip file works fine.

Can you please have a look and fix the issue?

Thank you

**Comment by cooliooau** [comment]
Hi, I think I have figured out the cause of the problem

In new version of the host.js file, these is one parameter short/missing when calling the CMD to open a local file. It will not open local file link with spaces in it.

Please fixed it ASAP.

Thanks

The parameter "Ttitle" is missing in the new host.js file.
![image](https://user-images.githubusercontent.com/51023646/136134466-6a991a33-a3ef-4673-9a9f-55bbedfd0efb.png)

**Comment by hashedtomato3** [comment]
Hi,

Thank you for reporting bug.
I fixed the issue and release as v1.0.9.

host.js is not changed from the previous versions, so I guess Windows
"start" command was updated.

Thanks

2021年10月6日(水) 12:09 cooliooau ***@***.***>:

**Comment by cooliooau** [comment]
The issues is fixed in the new release. Confirmed.
