### ISSUE TITLE
Cannot open files where file name contains #

### ISSUE THREAD

**Issue by cooliooau** [hashedtomato3/open-local-link#2]
**Problem**
For example, a file named **RFI#5 No. 58 (Fitout).pdf**, nothing happens when clicking on the file link. If remove the # in the file name, it works. 

If we use run start command in CMD, it can open the file.  It seems the issue is in the JS code that invokes the CMD. Can you please have a look and fix it?

Thank you.

**Comment by hashedtomato3** [comment]
Thank you for reporting an issue.
I will have a look.

**Comment by hashedtomato3** [comment]
I fixed the problem at version 1.0.11.
Please update the native client host.zip also.
